// you are given 2 number (a & b)
// Write a program to find the total number of set bits in these two numbers....(through Functions...)
// ex. 2=...10 and 3= ....11 the answer should be 3.....(1)... usually 1 is called setbits.....